apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup
spec:
  schedule: "*/2 * * * *"
  suspend: {{ .Values.tenant.enabledDBBackup }}
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: mariadb
            image: mariadb:latest
            imagePullPolicy: IfNotPresent
            command: ["/bin/sh", "-c"]
            args: 
            - mysqldump -u root -p$MARIADB_ROOT_PASSWORD -h wordpress-mysql --all-databases > /var/lib/mysql/alldbs.sql;
              date; echo all database has been backed up;
            env:
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password             

            volumeMounts:
            - name: cronjob-pv
              mountPath: /var/lib/mysql/
          volumes:
          - name: cronjob-pv
            persistentVolumeClaim:
              claimName: cronjob-pvclaim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cronjob-pvclaim
  labels:
    app: cronjob
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

