apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-wp
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: test1.wp.local
      http:
        paths:
          - path: /{{ .Values.tenant.ingress }}/(.*)
            pathType: Prefix
            backend:
              service:
                name: wordpress
                port:
                  number: 80
