apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: customer1
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
    tier: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: customer1
  labels:
    app: wordpress
spec:
  replicas: {{ .Values-override.tenants.customer1.wpReplicas }}
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - image: wordpress:4.8-apache
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: wordpress-mysql.customer1.svc.cluster.local
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wp-pass
              key: password
        - name: WORDPRESS_DB_USER
          value: "root"
        - name: WORDPRESS_DB_NAME
          value: "db"
        ports:
        - containerPort: 80
          name: wordpress